#!/bin/sh
# Apply defaults for Morse Micro radio0 without overwriting existing settings

dev="radio0"

uci set wireless.$dev.bcf='bcf_fgh100mhaamd.bin'
uci set wireless.$dev.enable_mcast_whitelist='0'
uci set wireless.$dev.enable_mcast_rate_control='1'
uci set wireless.$dev.country='US'

uci commit wireless

# Exit 0 so this script is removed from /etc/uci-defaults after first boot
exit 0